; ---------------------------------------------------------------------------

DACTable	struc ;	(sizeof=0x5)
StartOfs:	dw ?			; offset
DataLen:	dw ?
Bank:		db ?
DACTable	ends


;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	      Copyright	(c) 2011 Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 48-327F-7274-B7			    |
; |			       ESET spol. s r.o.			    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	50C7070DBFC65C59BB7EB22601318AAD
; Input	CRC32 :	EBC017E4

; ---------------------------------------------------------------------------
; File Name   :	D:\VStudio-Programme\VC2010\SMPSPlay\SMPS_Lib\Z80Drvs\Special\Virtua Fighter 2 (W) [!].bin
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 1436h Loaded length: 1436h

; Processor	  : z80	[]
; Target assembler: Zilog Macro	Assembler

; ===========================================================================

; Segment type:	Regular
		segment	RAM
		di
		di
		im	1
		jp	InitDriver
; ---------------------------------------------------------------------------
		align 8

; =============== S U B	R O U T	I N E =======================================


ReadPtrTable:				; CODE XREF: TrkUpdate_Proc+39p
					; TrkUpdate_Proc+55p ...
		ld	c, a
		ld	b, 0
		add	hl, bc
		add	hl, bc
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ret
; End of function ReadPtrTable

; ---------------------------------------------------------------------------
		align 8

; =============== S U B	R O U T	I N E =======================================


WriteFMIorII:				; CODE XREF: SendFMFreq+Fp
					; SendFMFreq+13p ...

; FUNCTION CHUNK AT 002E SIZE 00000002 BYTES

		bit	2, (ix+0)
		ret	nz
		add	a, (ix+1)
		bit	2, (ix+1)
		jr	nz, WriteFMIIPart
; End of function WriteFMIorII


; =============== S U B	R O U T	I N E =======================================


WriteFMI:				; CODE XREF: RAM:0065p	SendFMFreq+37p	...
		ld	(4000h), a
		ld	a, c
		ld	(4001h), a
		ret
; End of function WriteFMI

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR WriteFMIorII

WriteFMIIPart:				; CODE XREF: WriteFMIorII+Cj
		sub	4
; END OF FUNCTION CHUNK	FOR WriteFMIorII

; =============== S U B	R O U T	I N E =======================================


WriteFMII:				; CODE XREF: DoPause+137p
		ld	(4002h), a
		ld	a, c
		ld	(4003h), a
		ret
; End of function WriteFMII

; ---------------------------------------------------------------------------

VInt:
		di
		push	af
		push	hl
		push	de
		push	bc
		call	DoSoundQueue
		call	UpdateAll
		pop	bc
		pop	de
		pop	hl
		pop	af
		ret
; ---------------------------------------------------------------------------

InitDriver:				; CODE XREF: RAM:0004j
		ld	sp, 2000h
		ld	c, 0

loc_4D:					; CODE XREF: RAM:0052j
		ld	b, 0

loc_4F:					; CODE XREF: RAM:loc_4Fj
		djnz	$
		dec	c
		jr	nz, loc_4D
		call	StopAllSound
		ld	a, 74h
		ld	(byte_1C04), a
		ld	a, 76h
		ld	(byte_1C05), a
		ld	a, 2Bh
		ld	c, 80h
		call	WriteFMI
		ld	de, byte_F7F
		ld	bc, 8
		exx
		ld	de, byte_F7F
		ld	bc, 8
		ei
		jp	DACLoop

; =============== S U B	R O U T	I N E =======================================


UpdateAll:				; CODE XREF: RAM:0040p
		call	DoPause
		call	DoTempo
		call	DoFading
		call	PlaySoundID
		call	UpdateSFXTracks
		xor	a
		ld	(byte_1C19), a	; 00 - Music Mode
		ld	hl, byte_1C04
		ld	a, (hl)
		ld	hl, 6000h
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	ix, byte_1C40
		bit	7, (ix+0)
		call	nz, DrumUpdateTrack
		ld	b, 9
		ld	ix, unk_1C70
		jr	TrkUpdateLoop
; End of function UpdateAll


; =============== S U B	R O U T	I N E =======================================


UpdateSFXTracks:			; CODE XREF: UpdateAll+Cp
		ld	a, 1
		ld	(byte_1C19), a	; 01 - SFX Mode
		ld	hl, 6000h	; switch to Bank 3A8000
		xor	a		; Bank bits written: 075h
		ld	e, 1
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), e
		ld	(hl), e
		ld	(hl), a
		ld	(hl), a
		ld	ix, unk_1E20
		ld	b, 7
		call	TrkUpdateLoop
		ld	a, 80h
		ld	(byte_1C19), a	; 80 - Special SFX Mode
		ld	b, 1
		ld	ix, unk_1F70
; End of function UpdateSFXTracks


; =============== S U B	R O U T	I N E =======================================


TrkUpdateLoop:				; CODE XREF: UpdateAll+3Cj
					; UpdateSFXTracks+1Ap ...
		push	bc
		bit	7, (ix+0)
		call	nz, UpdateTrack
		ld	de, 30h
		add	ix, de
		pop	bc
		djnz	TrkUpdateLoop
		ret
; End of function TrkUpdateLoop


; =============== S U B	R O U T	I N E =======================================


UpdateTrack:				; CODE XREF: TrkUpdateLoop+5p

; FUNCTION CHUNK AT 0269 SIZE 00000019 BYTES
; FUNCTION CHUNK AT 0DAD SIZE 00000073 BYTES

		bit	7, (ix+1)
		jp	nz, UpdatePSGTrk
		call	TrackTimeout
		jr	nz, loc_113
		call	TrkUpdate_Proc
		bit	4, (ix+0)
		ret	nz
		call	PrepareModulat
		call	DoPitchSlide
		call	DoModulation
		call	SendFMFreq
		jp	DoNoteOn
; ---------------------------------------------------------------------------

loc_113:				; CODE XREF: UpdateTrack+Aj
		call	ExecPanAnim
		bit	4, (ix+0)
		ret	nz
		call	DoFMVolEnv
		ld	a, (ix+1Eh)
		or	a
		jr	z, loc_12A
		dec	(ix+1Eh)
		jp	z, DoNoteOff

loc_12A:				; CODE XREF: UpdateTrack+32j
		call	DoPitchSlide
		bit	6, (ix+0)
		ret	nz
		call	DoModulation
; End of function UpdateTrack


; =============== S U B	R O U T	I N E =======================================


SendFMFreq:				; CODE XREF: UpdateTrack+1Dp
		bit	2, (ix+0)
		ret	nz
		bit	0, (ix+0)
		jp	nz, loc_14A

loc_141:				; CODE XREF: SendFMFreq+1Aj
		ld	a, 0A4h
		ld	c, h
		rst	WriteFMIorII
		ld	a, 0A0h
		ld	c, l
		rst	WriteFMIorII
		ret
; ---------------------------------------------------------------------------

loc_14A:				; CODE XREF: SendFMFreq+9j
		ld	a, (ix+1)
		cp	2
		jr	nz, loc_141
		call	GetFM3FreqPtr
		ld	b, 4
		ld	hl, SpcFM3Regs

loc_159:				; CODE XREF: SendFMFreq+43j
		push	bc
		ld	a, (hl)
		inc	hl
		push	hl
		ex	de, hl
		ld	c, (hl)
		inc	hl
		ld	b, (hl)
		inc	hl
		ex	de, hl
		ld	l, (ix+0Dh)
		ld	h, (ix+0Eh)
		add	hl, bc
		push	af
		ld	c, h
		call	WriteFMI
		pop	af
		sub	4
		ld	c, l
		call	WriteFMI
		pop	hl
		pop	bc
		djnz	loc_159
		ret
; End of function SendFMFreq

; ---------------------------------------------------------------------------
SpcFM3Regs:	db 0ADh, 0AEh, 0ACh, 0A6h ; DATA XREF: SendFMFreq+21o

; =============== S U B	R O U T	I N E =======================================


GetFM3FreqPtr:				; CODE XREF: SendFMFreq+1Cp RAM:0CE6p
		ld	de, unk_1C2A
		ld	a, (byte_1C19)
		or	a
		ret	z
		ld	de, unk_1C1A
		ret	p
		ld	de, unk_1C22
		ret
; End of function GetFM3FreqPtr


; =============== S U B	R O U T	I N E =======================================


TrkUpdate_Proc:				; CODE XREF: UpdateTrack+Cp
					; UpdateTrack+CC2p
		ld	e, (ix+3)
		ld	d, (ix+4)
		res	1, (ix+0)
		res	4, (ix+0)

loc_19D:				; CODE XREF: RAM:09F1j
		ld	a, (de)
		inc	de
		cp	0E0h
		jp	nc, cfHandler
		ex	af, af'
		call	DoNoteOff
		call	DoPanAnimation
		ex	af, af'
		bit	3, (ix+0)
		jp	nz, DoRawFreqMode
		or	a
		jp	p, SetDuration
		sub	81h
		jp	p, GetNote
		call	SetRest
		jr	loc_1EF
; ---------------------------------------------------------------------------

GetNote:				; CODE XREF: TrkUpdate_Proc+2Aj
		add	a, (ix+5)
		ld	hl, PSGFreqs
		push	af
		rst	ReadPtrTable
		pop	af
		bit	7, (ix+1)
		jr	nz, loc_1E9
		push	de
		ld	d, 8
		ld	e, 0Ch
		ex	af, af'
		xor	a

loc_1D7:				; CODE XREF: TrkUpdate_Proc+4Ej
		ex	af, af'
		sub	e
		jr	c, loc_1E0
		ex	af, af'
		add	a, d
		jr	loc_1D7
; ---------------------------------------------------------------------------
		ex	af, af'

loc_1E0:				; CODE XREF: TrkUpdate_Proc+4Aj
		add	a, e
		ld	hl, FMFreqs
		rst	ReadPtrTable
		ex	af, af'
		or	h
		ld	h, a
		pop	de

loc_1E9:				; CODE XREF: TrkUpdate_Proc+3Fj
		ld	(ix+0Dh), l
		ld	(ix+0Eh), h

loc_1EF:				; CODE XREF: TrkUpdate_Proc+30j
		bit	5, (ix+0)
		jr	nz, loc_202
		ld	a, (de)
		or	a
		jp	p, loc_22E
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		jr	loc_235
; ---------------------------------------------------------------------------

loc_202:				; CODE XREF: TrkUpdate_Proc+64j
		ld	a, (de)
		inc	de
		ld	(ix+10h), a
		jr	loc_22D
; ---------------------------------------------------------------------------

DoRawFreqMode:				; CODE XREF: TrkUpdate_Proc+21j
		ld	h, a
		ld	a, (de)
		inc	de
		ld	l, a
		or	h
		jr	z, loc_21C
		ld	a, (ix+5)
		ld	b, 0
		or	a
		jp	p, loc_21A
		dec	b

loc_21A:				; CODE XREF: TrkUpdate_Proc+87j
		ld	c, a
		add	hl, bc

loc_21C:				; CODE XREF: TrkUpdate_Proc+7Fj
		ld	(ix+0Dh), l
		ld	(ix+0Eh), h
		bit	5, (ix+0)
		jr	z, loc_22D
		ld	a, (de)
		inc	de
		ld	(ix+10h), a

loc_22D:				; CODE XREF: TrkUpdate_Proc+78j
					; TrkUpdate_Proc+97j
		ld	a, (de)

loc_22E:				; CODE XREF: TrkUpdate_Proc+68j
		inc	de

SetDuration:				; CODE XREF: TrkUpdate_Proc+25j
					; DrumUpdate_Proc+36j
		call	TickMultiplier
		ld	(ix+0Ch), a

loc_235:				; CODE XREF: TrkUpdate_Proc+71j
					; DrumUpdate_Proc+40j
		ld	(ix+3),	e
		ld	(ix+4),	d
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		bit	1, (ix+0)
		ret	nz
		xor	a
		ld	(ix+25h), a
		ld	(ix+22h), a
		ld	(ix+17h), a
		ld	a, (ix+1Fh)
		ld	(ix+1Eh), a
		ret
; End of function TrkUpdate_Proc


; =============== S U B	R O U T	I N E =======================================


TickMultiplier:				; CODE XREF: TrkUpdate_Proc:SetDurationp
					; RAM:cfE8_NoteStopp
		ld	b, (ix+2)
		dec	b
		ret	z
		ld	c, a

loc_25D:				; CODE XREF: TickMultiplier+7j
		add	a, c
		djnz	loc_25D
		ret
; End of function TickMultiplier


; =============== S U B	R O U T	I N E =======================================


TrackTimeout:				; CODE XREF: UpdateTrack+7p
					; DrumUpdateTrackp ...
		ld	a, (ix+0Bh)
		dec	a
		ld	(ix+0Bh), a
		ret
; End of function TrackTimeout

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR UpdateTrack

DoNoteOn:				; CODE XREF: UpdateTrack+20j
		ld	a, (ix+0Dh)
		or	(ix+0Eh)
		ret	z
		ld	a, (ix+0)
		and	6
		ret	nz
		ld	a, (ix+1)
		or	0F0h
		ld	c, a
		ld	a, 28h
		call	WriteFMI
		ret
; END OF FUNCTION CHUNK	FOR UpdateTrack

; =============== S U B	R O U T	I N E =======================================


DoNoteOff:				; CODE XREF: UpdateTrack+37j
					; TrkUpdate_Proc+16p ...
		ld	a, (ix+0)
		and	6
		ret	nz

SendNoteOff:				; CODE XREF: RAM:0D49p
		ld	c, (ix+1)
		bit	7, c
		ret	nz
; End of function DoNoteOff

; START	OF FUNCTION CHUNK FOR SilenceFMChn

FMNoteOff:				; CODE XREF: SilenceFMChn+Dj
		ld	a, 28h
		call	WriteFMI
		res	6, (ix+0)
		ret
; END OF FUNCTION CHUNK	FOR SilenceFMChn

; =============== S U B	R O U T	I N E =======================================


DoPanAnimation:				; CODE XREF: TrkUpdate_Proc+19p
		ld	a, (ix+11h)
		dec	a
		ret	m
		jr	nz, loc_2DE
		bit	1, (ix+0)
		ret	nz

loc_2A4:				; CODE XREF: ExecPanAnim+6j
		dec	(ix+16h)
		ret	nz
		push	bc
		push	de
		push	hl
		ld	a, (ix+15h)
		ld	(ix+16h), a
		ld	a, (ix+12h)
		ld	hl, PanAniPtrList
		rst	ReadPtrTable
		ld	e, (ix+13h)
		inc	(ix+13h)
		ld	a, (ix+14h)
		dec	a
		cp	e
		jr	nz, loc_2D3
		dec	(ix+13h)
		ld	a, (ix+11h)
		cp	2
		jr	z, loc_2D3
		ld	(ix+13h), 0

loc_2D3:				; CODE XREF: DoPanAnimation+2Bj
					; DoPanAnimation+35j
		ld	d, 0
		add	hl, de
		ex	de, hl
		call	cfE0_Pan
		pop	hl
		pop	de
		pop	bc
		ret
; ---------------------------------------------------------------------------

loc_2DE:				; CODE XREF: DoPanAnimation+5j
		xor	a
		ld	(ix+13h), a
; End of function DoPanAnimation


; =============== S U B	R O U T	I N E =======================================


ExecPanAnim:				; CODE XREF: UpdateTrack:loc_113p
		ld	a, (ix+11h)
		sub	2
		ret	m
		jr	loc_2A4
; End of function ExecPanAnim

; ---------------------------------------------------------------------------
PanAniPtrList:	dw byte_2F2, byte_2F3, byte_2F4, byte_2F5 ; DATA XREF: DoPanAnimation+1Co
byte_2F2:	db 0C0h			; DATA XREF: RAM:PanAniPtrListo
byte_2F3:	db  80h			; DATA XREF: RAM:PanAniPtrListo
byte_2F4:	db 0C0h			; DATA XREF: RAM:PanAniPtrListo
byte_2F5:	db  40h,0C0h, 80h	; DATA XREF: RAM:PanAniPtrListo

; =============== S U B	R O U T	I N E =======================================


DoFMVolEnv:				; CODE XREF: UpdateTrack+2Bp
		ld	a, (ix+18h)
		or	a
		ret	z
		ret	m
		dec	a
		ld	hl, VolEnvPtrs
		rst	ReadPtrTable
		call	DoPSGVolEnv
		ld	h, (ix+1Dh)
		ld	l, (ix+1Ch)
		ld	de, Volume_Ops
		ld	b, 4
		ld	c, (ix+19h)

loc_314:				; CODE XREF: DoFMVolEnv+2Cj
		push	af
		sra	c
		push	bc
		jr	nc, loc_320
		add	a, (hl)
		and	7Fh
		ld	c, a
		ld	a, (de)
		rst	WriteFMIorII

loc_320:				; CODE XREF: DoFMVolEnv+20j
		pop	bc
		inc	de
		inc	hl
		pop	af
		djnz	loc_314
		ret
; End of function DoFMVolEnv


; =============== S U B	R O U T	I N E =======================================


PrepareModulat:				; CODE XREF: UpdateTrack+14p
					; UpdateTrack+CCAp
		bit	7, (ix+7)
		ret	z
		bit	1, (ix+0)
		ret	nz
		ld	e, (ix+20h)
		ld	d, (ix+21h)
		push	ix
		pop	hl
		ld	b, 0
		ld	c, 24h
		add	hl, bc
		ex	de, hl
		ldi
		ldi
		ldi
		ld	a, (hl)
		srl	a
		ld	(de), a
		xor	a
		ld	(ix+22h), a
		ld	(ix+23h), a
		ret
; End of function PrepareModulat


; =============== S U B	R O U T	I N E =======================================


DoModulation:				; CODE XREF: UpdateTrack+1Ap
					; UpdateTrack+42p ...
		ld	a, (ix+7)
		or	a
		ret	z
		cp	80h
		jr	nz, DoModEnv
		dec	(ix+24h)
		ret	nz
		inc	(ix+24h)
		push	hl
		ld	l, (ix+22h)
		ld	h, (ix+23h)
		ld	e, (ix+20h)
		ld	d, (ix+21h)
		push	de
		pop	iy
		dec	(ix+25h)
		jr	nz, loc_38E
		ld	a, (iy+1)
		ld	(ix+25h), a
		ld	a, (ix+26h)
		ld	c, a
		and	80h
		rlca
		neg
		ld	b, a
		add	hl, bc
		ld	(ix+22h), l
		ld	(ix+23h), h

loc_38E:				; CODE XREF: DoModulation+23j
		pop	bc
		add	hl, bc
		dec	(ix+27h)
		ret	nz
		ld	a, (iy+3)
		ld	(ix+27h), a
		ld	a, (ix+26h)
		neg
		ld	(ix+26h), a
		ret
; ---------------------------------------------------------------------------

DoModEnv:				; CODE XREF: DoModulation+7j
		dec	a
		ex	de, hl
		ld	hl, ModEnvPtrs
		rst	ReadPtrTable
		jr	loc_3AE
; ---------------------------------------------------------------------------

loc_3AB:				; CODE XREF: DoModulation+82j
					; DoModulation+85j
		ld	(ix+25h), a

loc_3AE:				; CODE XREF: DoModulation+57j
					; DoModulation+95j
		push	hl
		ld	c, (ix+25h)
		ld	b, 0
		add	hl, bc
		ld	a, (hl)
		pop	hl
		bit	7, a
		jp	z, ModEnv_Positive
		cp	82h
		jr	z, ModEnv_Jump2Idx
		cp	80h
		jr	z, ModEnv_Reset
		cp	84h
		jr	z, ModEnv_ChgMult
		ld	h, 0FFh
		jr	nc, ModEnv_Next
		set	6, (ix+0)
		pop	hl
		ret
; ---------------------------------------------------------------------------

ModEnv_Jump2Idx:			; CODE XREF: DoModulation+6Cj
		inc	bc
		ld	a, (bc)
		jr	loc_3AB
; ---------------------------------------------------------------------------

ModEnv_Reset:				; CODE XREF: DoModulation+70j
		xor	a
		jr	loc_3AB
; ---------------------------------------------------------------------------

ModEnv_ChgMult:				; CODE XREF: DoModulation+74j
		inc	bc
		ld	a, (bc)
		add	a, (ix+22h)
		ld	(ix+22h), a
		inc	(ix+25h)
		inc	(ix+25h)
		jr	loc_3AE
; ---------------------------------------------------------------------------

ModEnv_Positive:			; CODE XREF: DoModulation+67j
		ld	h, 0

ModEnv_Next:				; CODE XREF: DoModulation+78j
		ld	l, a
		ld	b, (ix+22h)
		inc	b
		ex	de, hl

loc_3F1:				; CODE XREF: DoModulation+A0j
		add	hl, de
		djnz	loc_3F1
		inc	(ix+25h)
		ret
; End of function DoModulation


; =============== S U B	R O U T	I N E =======================================


DoPitchSlide:				; CODE XREF: UpdateTrack+17p
					; UpdateTrack:loc_12Ap	...
		ld	b, 0
		ld	a, (ix+10h)
		or	a
		jp	p, loc_402
		dec	b

loc_402:				; CODE XREF: DoPitchSlide+6j
		ld	h, (ix+0Eh)
		ld	l, (ix+0Dh)
		ld	c, a
		add	hl, bc
		bit	7, (ix+1)
		jr	nz, loc_432
		ex	de, hl
		ld	a, 7
		and	d
		ld	b, a
		ld	c, e
		or	a
		ld	hl, 283h
		sbc	hl, bc
		jr	c, loc_424
		ld	hl, -57Bh
		add	hl, de
		jr	loc_432
; ---------------------------------------------------------------------------

loc_424:				; CODE XREF: DoPitchSlide+24j
		or	a
		ld	hl, 508h
		sbc	hl, bc
		jr	nc, loc_431
		ld	hl, 57Ch
		add	hl, de
		ex	de, hl

loc_431:				; CODE XREF: DoPitchSlide+32j
		ex	de, hl

loc_432:				; CODE XREF: DoPitchSlide+16j
					; DoPitchSlide+2Aj
		bit	5, (ix+0)
		ret	z
		ld	(ix+0Eh), h
		ld	(ix+0Dh), l
		ret
; End of function DoPitchSlide


; =============== S U B	R O U T	I N E =======================================


GetFMInsPtr:				; CODE XREF: SetInsFromSong+1Bp
		ld	hl, (word_1C37)
		ld	a, (byte_1C19)
		or	a
		jr	z, JumpToInsData
		ld	l, (ix+2Ah)
		ld	h, (ix+2Bh)
; End of function GetFMInsPtr


; =============== S U B	R O U T	I N E =======================================


JumpToInsData:				; CODE XREF: GetFMInsPtr+7j
					; SetInsFromSong+14p ...
		xor	a
		or	b
		ret	z
		ld	de, 19h

loc_453:				; CODE XREF: JumpToInsData+7j
		add	hl, de
		djnz	loc_453
		ret
; End of function JumpToInsData

; ---------------------------------------------------------------------------
FMInsOperators:	db 0B0h			; DATA XREF: SendFMInso
		db  30h, 38h, 34h, 3Ch
		db  50h, 58h, 54h, 5Ch
		db  60h, 68h, 64h, 6Ch
		db  70h, 78h, 74h, 7Ch
		db  80h, 88h, 84h, 8Ch
Volume_Ops:	db  40h, 48h, 44h, 4Ch	; DATA XREF: DoFMVolEnv+14o
					; RefreshVolume+1o
SSGEG_Ops:	db  90h, 98h, 94h, 9Ch	; DATA XREF: SendSSGEGo

; =============== S U B	R O U T	I N E =======================================


SendFMIns:				; CODE XREF: SetInsFromSong:loc_B50p
					; PlaySoundID+765p
		ld	de, FMInsOperators
		ld	c, (ix+0Ah)
		ld	a, 0B4h
		rst	WriteFMIorII
		call	WriteInsReg
		ld	(ix+1Bh), a
		ld	b, 14h

loc_485:				; CODE XREF: SendFMIns+14j
		call	WriteInsReg
		djnz	loc_485
		ld	(ix+1Ch), l
		ld	(ix+1Dh), h
		jp	RefreshVolume
; End of function SendFMIns


; =============== S U B	R O U T	I N E =======================================


WriteInsReg:				; CODE XREF: SendFMIns+9p
					; SendFMIns:loc_485p
		ld	a, (de)
		inc	de
		ld	c, (hl)
		inc	hl
		rst	18h
		ret
; End of function WriteInsReg


; =============== S U B	R O U T	I N E =======================================


PlaySoundID:				; CODE XREF: UpdateAll+9p

; FUNCTION CHUNK AT 05B3 SIZE 000000BC BYTES
; FUNCTION CHUNK AT 0B73 SIZE 000000C6 BYTES

		ld	a, (byte_1C09)
		bit	7, a
		jp	z, StopAllSound	; 00-7F	- Stop All
		cp	0A0h
		jp	c, PlayMusic	; 80-9F	- Music
		cp	0E9h
		jp	c, PlaySFX	; A0-E8	- SFX
		cp	0F0h
		jp	c, PlaySpcSFX	; E9-EF	- Special SFX
		cp	0FFh
		jp	nc, StopAllSound ; F9-FF - Stop	All

PlaySnd_Command:			; F0-F8	- Special Commands
		sub	0F0h
		ld	hl, CmdPtrTable
		rst	ReadPtrTable
		xor	a
		ld	(byte_1C18), a
		jp	(hl)
; ---------------------------------------------------------------------------
CmdPtrTable:				; DATA XREF: PlaySoundID+1Eo
		dw FadeOutMusic, StopAllSound, SilencePSG, StopSpcSFX
; ---------------------------------------------------------------------------

StopSpcSFX:				; DATA XREF: PlaySoundID:CmdPtrTableo
		ld	ix, unk_1F70
		ld	b, 2
		ld	a, 80h
		ld	(byte_1C19), a

loc_4D3:				; CODE XREF: PlaySoundID+48j
		push	bc
		bit	7, (ix+0)
		call	nz, loc_4E4
		ld	de, 30h
		add	ix, de
		pop	bc
		djnz	loc_4D3
		ret
; ---------------------------------------------------------------------------

loc_4E4:				; CODE XREF: PlaySoundID+3Fp
		push	hl
		push	hl
		jp	cfF2_StopTrk
; ---------------------------------------------------------------------------

PlayMusic:				; CODE XREF: PlaySoundID+Aj
		sub	81h
		ret	m
		ex	af, af'
		call	StopAllSound
		ex	af, af'
		push	af
		ld	hl, MusicBanks
		add	a, l
		ld	l, a
		adc	a, h
		sub	l
		ld	h, a
		ld	a, (hl)
		ld	(byte_1C04), a
		ld	hl, byte_1C04
		ld	a, (hl)
		ld	hl, 6000h
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		pop	af
		ld	hl, MusicPtrs
		rst	ReadPtrTable
		push	hl
		push	hl
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ld	(word_1C37), hl
		pop	hl
		pop	iy
		ld	a, (iy+5)
		ld	(byte_1C13), a
		ld	(byte_1C14), a
		ld	de, 6
		add	hl, de
		ld	(word_1C33), hl
		ld	hl, FMInitBytes
		ld	(word_1C35), hl
		ld	de, byte_1C40
		ld	b, (iy+2)
		ld	a, (iy+4)

loc_546:				; CODE XREF: PlaySoundID+CCj
		push	bc
		ld	hl, (word_1C35)
		ldi
		ldi
		ld	(de), a
		inc	de
		ld	(word_1C35), hl
		ld	hl, (word_1C33)
		ldi
		ldi
		ldi
		ldi
		ld	(word_1C33), hl
		call	FinishFMTrkInit
		pop	bc
		djnz	loc_546
		ld	a, (iy+3)
		or	a
		jp	z, ClearSoundID
		ld	b, a
		ld	hl, PSGInitBytes
		ld	(word_1C35), hl
		ld	de, byte_1D90
		ld	a, (iy+4)

loc_57B:				; CODE XREF: PlaySoundID+FEj
		push	bc
		ld	hl, (word_1C35)
		ldi
		ldi
		ld	(de), a
		inc	de
		ld	(word_1C35), hl
		ld	hl, (word_1C33)
		ld	bc, 6
		ldir
		ld	(word_1C33), hl
		call	FinishTrkInit
		pop	bc
		djnz	loc_57B
; End of function PlaySoundID

; START	OF FUNCTION CHUNK FOR StopAllSound

ClearSoundID:				; CODE XREF: PlaySoundID+D2j
					; PlaySoundID+1D3j ...
		ld	a, 80h
		ld	(byte_1C09), a
		ret
; END OF FUNCTION CHUNK	FOR StopAllSound
; ---------------------------------------------------------------------------
FMInitBytes:	db  80h,   6		; DATA XREF: PlaySoundID+9Eo
					; StopAllSound+Do
		db  80h,   0
		db  80h,   1
		db  80h,   2
		db  80h,   4
		db  80h,   5
		db  80h,   6
PSGInitBytes:	db  80h, 80h		; DATA XREF: PlaySoundID+D6o
		db  80h,0A0h
		db  80h,0C0h
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR PlaySoundID

PlaySpcSFX:				; CODE XREF: PlaySoundID+14j
		ex	af, af'
		ld	hl, 6000h
		xor	a
		ld	e, 1
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), e
		ld	(hl), e
		ld	(hl), a
		ld	(hl), a
		ex	af, af'
		sub	0E9h
		ex	af, af'
		ld	a, 80h
		ld	hl, SpcSFXPtrs
		jr	loc_5E6
; ---------------------------------------------------------------------------

PlaySFX:				; CODE XREF: PlaySoundID+Fj
		ex	af, af'
		ld	hl, 6000h
		xor	a
		ld	e, 1
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), e
		ld	(hl), e
		ld	(hl), a
		ld	(hl), a
		ex	af, af'
		sub	0A0h
		ex	af, af'
		xor	a
		ld	hl, SFXPtrs

loc_5E6:				; CODE XREF: PlaySoundID+133j
		ld	(byte_1C19), a
		ex	af, af'
		rst	8
		push	hl
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ld	(word_1C39), hl
		xor	a
		ld	(byte_1C15), a
		pop	hl
		push	hl
		pop	iy
		ld	a, (iy+2)
		ld	(byte_1C3B), a
		ld	de, 4
		add	hl, de
		ld	b, (iy+3)

loc_608:				; CODE XREF: PlaySoundID+1D1j
		push	bc
		push	hl
		inc	hl
		ld	c, (hl)
		call	GetSFXChnPtrs
		set	2, (hl)
		push	ix
		ld	a, (byte_1C19)
		or	a
		jr	z, loc_61C
		pop	hl
		push	iy

loc_61C:				; CODE XREF: PlaySoundID+17Ej
		pop	de
		pop	hl
		ldi
		ld	a, (de)
		cp	2
		call	z, ResetSpcFM3Mode
		ldi
		ld	a, (byte_1C3B)
		ld	(de), a
		inc	de
		ldi
		ldi
		ldi
		ldi
		call	FinishFMTrkInit
		bit	7, (ix+0)
		jr	z, loc_64A
		ld	a, (ix+1)
		cp	(iy+1)
		jr	nz, loc_64A
		set	2, (iy+0)

loc_64A:				; CODE XREF: PlaySoundID+1A3j
					; PlaySoundID+1ABj
		push	hl
		ld	hl, (word_1C39)
		ld	a, (byte_1C19)
		or	a
		jr	z, loc_658
		push	iy
		pop	ix

loc_658:				; CODE XREF: PlaySoundID+1B9j
		ld	(ix+2Ah), l
		ld	(ix+2Bh), h
		call	DoNoteOff
		bit	7, (ix+1)
		call	z, DisableSSGEG
		pop	hl
		pop	bc
		djnz	loc_608
		jp	ClearSoundID
; END OF FUNCTION CHUNK	FOR PlaySoundID

; =============== S U B	R O U T	I N E =======================================


GetSFXChnPtrs:				; CODE XREF: PlaySoundID+173p
					; PlaySoundID+6EBp
		bit	7, c
		jr	nz, loc_67B
		ld	a, c
		bit	2, a
		jr	z, loc_692
		dec	a
		jr	loc_692
; ---------------------------------------------------------------------------

loc_67B:				; CODE XREF: GetSFXChnPtrs+2j
		ld	a, 1Fh
		call	SilencePSGChn
		ld	a, 0FFh
		ld	(7F11h), a
		ld	a, c
		srl	a
		srl	a
		srl	a
		srl	a
		srl	a
		add	a, 2

loc_692:				; CODE XREF: GetSFXChnPtrs+7j
					; GetSFXChnPtrs+Aj
		sub	2
		ld	(byte_1C32), a
		push	af
		ld	hl, SFXChnPtrs
		rst	ReadPtrTable
		push	hl
		pop	ix
		pop	af
		push	af
		ld	hl, SpcSFXChnPtrs
		rst	ReadPtrTable
		push	hl
		pop	iy
		pop	af
		ld	hl, BGMChnPtrs
		rst	ReadPtrTable
		ret
; End of function GetSFXChnPtrs


; =============== S U B	R O U T	I N E =======================================


FinishFMTrkInit:			; CODE XREF: PlaySoundID+C8p
					; PlaySoundID+19Cp
		ex	af, af'
		xor	a
		ld	(de), a
		inc	de
		ld	(de), a
		inc	de
		ex	af, af'
; End of function FinishFMTrkInit


; =============== S U B	R O U T	I N E =======================================


FinishTrkInit:				; CODE XREF: PlaySoundID+FAp
		ex	de, hl
		ld	(hl), 30h
		inc	hl
		ld	(hl), 0C0h
		inc	hl
		ld	(hl), 1
		ld	b, 24h

loc_6C0:				; CODE XREF: FinishTrkInit+Ej
		inc	hl
		ld	(hl), 0
		djnz	loc_6C0
		inc	hl
		ex	de, hl
		ret
; End of function FinishTrkInit

; ---------------------------------------------------------------------------
SpcSFXChnPtrs:	dw 1F70h, 1F70h, 1F70h,	1F70h, 1F70h, 1F70h, 1F70h, 1F70h
					; DATA XREF: GetSFXChnPtrs+32o
SFXChnPtrs:	dw 1E20h, 1E50h, 1E80h,	1EB0h, 1EE0h, 1F10h, 1F40h, 1F40h
					; DATA XREF: GetSFXChnPtrs+29o
BGMChnPtrs:	dw 1CD0h, 1D00h, 1D30h,	1D60h, 1D90h, 1DC0h, 1DF0h, 1DF0h
					; DATA XREF: GetSFXChnPtrs+3Ao

; =============== S U B	R O U T	I N E =======================================


DoPause:				; CODE XREF: UpdateAllp

; FUNCTION CHUNK AT 0817 SIZE 0000002F BYTES

		ld	hl, unk_1C10
		ld	a, (hl)
		or	a
		ret	z
		jp	m, loc_709
		pop	de
		dec	a
		ret	nz
		ld	(hl), 2
		jp	SilenceAll
; ---------------------------------------------------------------------------

loc_709:				; CODE XREF: DoPause+6j
		xor	a
		ld	(hl), a
		ld	a, (byte_1C0D)
		or	a
		jp	nz, StopAllSound
		ld	ix, byte_1C40
		ld	b, 7

loc_718:				; CODE XREF: DoPause+37j
		ld	a, (byte_1C11)
		or	a
		jr	nz, loc_724
		bit	7, (ix+0)
		jr	z, loc_72A

loc_724:				; CODE XREF: DoPause+24j
		ld	c, (ix+0Ah)
		ld	a, 0B4h
		rst	WriteFMIorII

loc_72A:				; CODE XREF: DoPause+2Aj
		ld	de, 30h
		add	ix, de
		djnz	loc_718
		ld	ix, unk_1E20
		ld	b, 8

loc_737:				; CODE XREF: DoPause+56j
		bit	7, (ix+0)
		jr	z, loc_749
		bit	7, (ix+1)
		jr	nz, loc_749
		ld	c, (ix+0Ah)
		ld	a, 0B4h
		rst	WriteFMIorII

loc_749:				; CODE XREF: DoPause+43j DoPause+49j
		ld	de, 30h
		add	ix, de
		djnz	loc_737
		ret
; End of function DoPause

; ---------------------------------------------------------------------------

FadeOutMusic:				; DATA XREF: PlaySoundID:CmdPtrTableo
		ld	a, 28h
		ld	(byte_1C0D), a
		ld	a, 6
		ld	(byte_1C0F), a
		ld	(byte_1C0E), a

; =============== S U B	R O U T	I N E =======================================


StopDrumPSG:				; CODE XREF: DoFading+6p
		xor	a
		ld	(byte_1C40), a
		ld	(byte_1D60), a
		ld	(byte_1DF0), a
		ld	(byte_1D90), a
		ld	(byte_1DC0), a
		jp	SilencePSG
; End of function StopDrumPSG


; =============== S U B	R O U T	I N E =======================================


DoFading:				; CODE XREF: UpdateAll+6p
		ld	hl, byte_1C0D
		ld	a, (hl)
		or	a
		ret	z
		call	m, StopDrumPSG
		res	7, (hl)
		ld	a, (byte_1C0F)
		dec	a
		jr	z, ApplyFading
		ld	(byte_1C0F), a
		ret
; ---------------------------------------------------------------------------

ApplyFading:				; CODE XREF: DoFading+Fj
		ld	a, (byte_1C0E)
		ld	(byte_1C0F), a
		ld	a, (byte_1C0D)
		dec	a
		ld	(byte_1C0D), a
		jr	z, StopAllSound
		ld	hl, 1C04h
		ld	a, (hl)
		ld	hl, 6000h
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	hl, byte_1C07
		inc	(hl)
		ld	ix, byte_1C40
		ld	b, 6

loc_7B7:				; CODE XREF: DoFading+5Cj
		bit	7, (ix+0)
		jr	z, loc_7C8
		bit	2, (ix+0)
		jr	nz, loc_7C8
		push	bc
		call	RefreshVolume
		pop	bc

loc_7C8:				; CODE XREF: DoFading+4Aj DoFading+50j
		ld	de, 30h
		add	ix, de
		djnz	loc_7B7
		ret
; End of function DoFading


; =============== S U B	R O U T	I N E =======================================


StopAllSound:				; CODE XREF: RAM:0054p	PlaySoundID+5j	...

; FUNCTION CHUNK AT 0599 SIZE 00000006 BYTES

		ld	hl, byte_1C09
		ld	de, unk_1C0A
		ld	bc, 396h
		ld	(hl), 0
		ldir
		ld	ix, FMInitBytes
		ld	b, 6

loc_7E3:				; CODE XREF: StopAllSound+1Fj
		push	bc
		call	SilenceFMChn
		call	DisableSSGEG
		inc	ix
		inc	ix
		pop	bc
		djnz	loc_7E3
		ld	b, 7
		xor	a
		ld	(byte_1C07), a
		ld	(byte_1C3C), a
		ld	(byte_1C3D), a
		ld	(byte_1C0D), a
		call	SilencePSG

ResetSpcFM3Mode:			; CODE XREF: PlaySoundID+18Ap
		xor	a
		ld	(byte_1C12), a
		ld	c, a
		ld	a, 27h
		call	WriteFMI
		jp	ClearSoundID
; End of function StopAllSound


; =============== S U B	R O U T	I N E =======================================


DisableSSGEG:				; CODE XREF: PlaySoundID+1CCp
					; StopAllSound+17p
		ld	a, 90h
		ld	c, 0
		jp	SendAllFMOps
; End of function DisableSSGEG

; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR DoPause

SilenceAll:				; CODE XREF: DoPause+Ej
		call	SilencePSG
		push	bc
		push	af
		ld	b, 3
		ld	a, 0B4h
		ld	c, 0

loc_822:				; CODE XREF: DoPause+130j
		push	af
		call	WriteFMI
		pop	af
		inc	a
		djnz	loc_822
		ld	b, 3
		ld	a, 0B4h

loc_82E:				; CODE XREF: DoPause+13Cj
		push	af
		call	WriteFMII
		pop	af
		inc	a
		djnz	loc_82E
		ld	c, 0
		ld	b, 7
		ld	a, 28h

loc_83C:				; CODE XREF: DoPause+14Aj
		push	af
		call	WriteFMI
		inc	c
		pop	af
		djnz	loc_83C
		pop	af
		pop	bc
; END OF FUNCTION CHUNK	FOR DoPause

; =============== S U B	R O U T	I N E =======================================


SilencePSG:				; CODE XREF: StopDrumPSG+10j
					; StopAllSound+30p ...
		push	bc
		ld	b, 4
		ld	a, 9Fh

loc_84B:				; CODE XREF: SilencePSG+Aj
		ld	(7F11h), a
		add	a, 20h
		djnz	loc_84B
		pop	bc
		jp	ClearSoundID
; End of function SilencePSG


; =============== S U B	R O U T	I N E =======================================


DoTempo:				; CODE XREF: UpdateAll+3p
		ld	a, (byte_1C14)
		ld	hl, byte_1C13
		add	a, (hl)
		ld	(hl), a
		ret	nc
		ld	hl, unk_1C4B
		ld	de, 30h
		ld	b, 0Ah

loc_867:				; CODE XREF: DoTempo+13j
		inc	(hl)
		add	hl, de
		djnz	loc_867
		ret
; End of function DoTempo


; =============== S U B	R O U T	I N E =======================================


DoSoundQueue:				; CODE XREF: RAM:003Dp
		ld	a, r
		ld	(byte_1C17), a
		ld	de, 1C0Ah
		ld	b, 3

loc_876:				; CODE XREF: DoSoundQueue+32j
		ld	a, (de)
		ld	c, a
		bit	7, a
		jr	z, loc_89B
		sub	9Fh
		jp	c, loc_8A1
		sub	1
		ld	hl, SndPriorities
		add	a, l
		ld	l, a
		adc	a, h
		sub	l
		ld	h, a
		ld	a, (byte_1C18)
		cp	(hl)
		jr	z, loc_893
		jr	nc, loc_89B

loc_893:				; CODE XREF: DoSoundQueue+23j
		ld	a, c
		ld	(byte_1C09), a
		ld	a, (hl)
		ld	(byte_1C18), a

loc_89B:				; CODE XREF: DoSoundQueue+Ej
					; DoSoundQueue+25j
		xor	a
		ld	(de), a
		inc	de
		djnz	loc_876
		ret
; ---------------------------------------------------------------------------

loc_8A1:				; CODE XREF: DoSoundQueue+12j
		ld	a, c
		ld	(byte_1C09), a
		xor	a
		ld	(byte_1C18), a
		ld	de, unk_1C0A
		ld	(de), a
		inc	de
		ld	(de), a
		inc	de
		ld	(de), a
		ret
; End of function DoSoundQueue


; =============== S U B	R O U T	I N E =======================================


SilenceFMChn:				; CODE XREF: StopAllSound+14p
					; RAM:cfE3_SilenceTrkp

; FUNCTION CHUNK AT 028E SIZE 0000000A BYTES

		call	SetMaxRelRate
		ld	a, 40h
		ld	c, 7Fh
		call	SendAllFMOps
		ld	c, (ix+1)
		jp	FMNoteOff
; End of function SilenceFMChn


; =============== S U B	R O U T	I N E =======================================


SetMaxRelRate:				; CODE XREF: SilenceFMChnp RAM:0B22p
		ld	a, 80h
		ld	c, 0FFh
; End of function SetMaxRelRate


; =============== S U B	R O U T	I N E =======================================


SendAllFMOps:				; CODE XREF: DisableSSGEG+4j
					; SilenceFMChn+7p
		ld	b, 4

loc_8C8:				; CODE XREF: SendAllFMOps+7j
		push	af
		rst	WriteFMIorII
		pop	af
		add	a, 4
		djnz	loc_8C8
		ret
; End of function SendAllFMOps

; ---------------------------------------------------------------------------
PSGFreqs:	dw  3FFh, 3FFh,	3FFh, 3FFh, 3FFh, 3FFh,	3FFh, 3FFh, 3FFh, 3F7h,	3BEh, 388h
					; DATA XREF: TrkUpdate_Proc+35o
		dw  356h, 326h,	2F9h, 2CEh, 2A5h, 280h,	25Ch, 23Ah, 21Ah, 1FBh,	1DFh, 1C4h
		dw  1ABh, 193h,	17Dh, 167h, 153h, 140h,	12Eh, 11Dh, 10Dh, 0FEh,	0EFh, 0E2h
		dw  0D6h, 0C9h,	0BEh, 0B4h, 0A9h, 0A0h,	 97h,  8Fh,  87h,  7Fh,	 78h,  71h
		dw   6Bh,  65h,	 5Fh,  5Ah,  55h,  50h,	 4Bh,  47h,  43h,  40h,	 3Ch,  39h
		dw   36h,  33h,	 30h,  2Dh,  2Bh,  28h,	 26h,  24h,  22h,  20h,	 1Fh,  1Dh
		dw   1Bh,  1Ah,	 18h,  17h,  16h,  15h,	 13h,  12h,  11h,  10h,	   0,	 0
FMFreqs:	dw  284h, 2ABh,	2D3h, 2FEh, 32Dh, 35Ch,	38Fh, 3C5h, 3FFh, 43Ch,	47Ch, 4C0h
					; DATA XREF: TrkUpdate_Proc+52o

; =============== S U B	R O U T	I N E =======================================


DrumUpdateTrack:			; CODE XREF: UpdateAll+33p
		call	TrackTimeout
		call	z, DrumUpdate_Proc
		ret
; End of function DrumUpdateTrack


; =============== S U B	R O U T	I N E =======================================


DrumUpdate_Proc:			; CODE XREF: DrumUpdateTrack+3p
		ld	e, (ix+3)
		ld	d, (ix+4)

loc_99D:				; CODE XREF: DrumUpdate_Proc+4Aj
		ld	a, (de)
		inc	de
		cp	0E0h
		jp	nc, cfHandler_Drum
		or	a
		jp	m, loc_9AC
		dec	de
		ld	a, (ix+0Dh)

loc_9AC:				; CODE XREF: DrumUpdate_Proc+Ej
		ld	(ix+0Dh), a
		or	a
		jp	p, loc_9CA
		push	de
		sub	80h
		jp	z, loc_9C9
		ex	af, af'
		call	DoNoteOff
		ex	af, af'
		ld	hl, byte_1C40
		bit	2, (hl)
		jp	nz, loc_9C9
		ld	(byte_1C08), a

loc_9C9:				; CODE XREF: DrumUpdate_Proc+1Fj
					; DrumUpdate_Proc+2Cj
		pop	de

loc_9CA:				; CODE XREF: DrumUpdate_Proc+19j
		ld	a, (de)
		inc	de
		or	a
		jp	p, SetDuration
		dec	de
		ld	a, (ix+0Ch)
		ld	(ix+0Bh), a
		jp	loc_235
; ---------------------------------------------------------------------------

cfHandler_Drum:				; CODE XREF: DrumUpdate_Proc+Aj
		ld	hl, cfReturn_Drum
		jp	loc_9E7
; ---------------------------------------------------------------------------

cfReturn_Drum:				; DATA XREF: DrumUpdate_Proc:cfHandler_Drumo
		inc	de
		jp	loc_99D
; ---------------------------------------------------------------------------

cfHandler:				; CODE XREF: TrkUpdate_Proc+12j
		ld	hl, cfReturn

loc_9E7:				; CODE XREF: DrumUpdate_Proc+46j
		push	hl
		sub	0E0h
		ld	hl, cfPtrTable
		rst	ReadPtrTable
		ld	a, (de)
		jp	(hl)
; End of function DrumUpdate_Proc

; ---------------------------------------------------------------------------

cfReturn:				; DATA XREF: DrumUpdate_Proc:cfHandlero
		inc	de
		jp	loc_19D
; ---------------------------------------------------------------------------
cfPtrTable:	dw cfE0_Pan, cfE1_Detune, cfE2_SetComm,	cfE3_SilenceTrk
					; DATA XREF: DrumUpdate_Proc+53o
		dw cfE4_PanAnim, cfE5_ChgPFMVol, cfE6_ChgFMVol,	cfE7_Hold
		dw cfE8_NoteStop, cfE9_SetLFO, cfEA_PlayDAC, cfEB_LoopExit
		dw cfEC_ChgPSGVol, cfED_FMChnWrite, cfEE_FM1Write, cfEF_SetIns
		dw cfF0_ModSetup, cfF1_ModTypePFM, cfF2_StopTrk, cfF3_PSGNoise
		dw cfF4_ModType, cfF5_SetPSGIns, cfF6_GoTo, cfF7_Loop
		dw cfF8_GoSub, cfF9_Return, cfFA_TickMult, cfFB_ChgTransp
		dw cfFC_PitchSlide, cfFD_RawFrqMode, cfFE_SpcFM3Mode, cfMetaCoordFlag
cfMetaPtrTable:	dw cf00_SetTempo, cf01_PlaySnd,	cf02_MusPause, cf03_CopyMem
					; DATA XREF: RAM:cfMetaCoordFlago
		dw cf04_TickMulAll, cf05_SSGEG,	cf06_FMVolEnv
; ---------------------------------------------------------------------------

cfEA_PlayDAC:				; DATA XREF: RAM:cfPtrTableo
		ld	(byte_1C3D), a
		ld	hl, byte_1C40
		set	2, (hl)
		ret

; =============== S U B	R O U T	I N E =======================================


cfE0_Pan:				; CODE XREF: DoPanAnimation+3Fp
					; DATA XREF: RAM:cfPtrTableo
		ld	c, 3Fh

loc_A4D:				; CODE XREF: RAM:0A65j
		ld	a, (ix+0Ah)
		and	c
		ex	de, hl
		or	(hl)
		ld	(ix+0Ah), a
		ld	c, a
		ld	a, 0B4h
		rst	WriteFMIorII
		ex	de, hl
		ret
; End of function cfE0_Pan

; ---------------------------------------------------------------------------

cfE9_SetLFO:				; DATA XREF: RAM:cfPtrTableo
		ld	c, a
		ld	a, 22h
		call	WriteFMI
		inc	de
		ld	c, 0C0h
		jr	loc_A4D
; ---------------------------------------------------------------------------

cfE1_Detune:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+10h), a
		ret
; ---------------------------------------------------------------------------

cfE2_SetComm:				; DATA XREF: RAM:cfPtrTableo
		ld	(byte_1C16), a
		ret
; ---------------------------------------------------------------------------

cfE3_SilenceTrk:			; DATA XREF: RAM:cfPtrTableo
		call	SilenceFMChn
		jp	cfF2_StopTrk
; ---------------------------------------------------------------------------

cfE4_PanAnim:				; DATA XREF: RAM:cfPtrTableo
		push	ix
		pop	hl
		ld	bc, 11h
		add	hl, bc
		ex	de, hl
		ld	bc, 5
		ldir
		ld	a, 1
		ld	(de), a
		ex	de, hl
		dec	de
		ret
; ---------------------------------------------------------------------------

cfE5_ChgPFMVol:				; DATA XREF: RAM:cfPtrTableo
		inc	de
		add	a, (ix+6)
		ld	(ix+6),	a
		ld	a, (de)

cfE6_ChgFMVol:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	nz
		add	a, (ix+6)
		ld	(ix+6),	a

; =============== S U B	R O U T	I N E =======================================


RefreshVolume:				; CODE XREF: SendFMIns+1Cj
					; DoFading+53p
		push	de
		ld	de, Volume_Ops
		ld	l, (ix+1Ch)
		ld	h, (ix+1Dh)
		ld	b, 4

loc_AA7:				; CODE XREF: RefreshVolume+2Bj
		ld	a, (hl)
		or	a
		jp	p, loc_ABF
		add	a, (ix+6)
		jp	m, loc_AB4
		ld	a, 0FFh

loc_AB4:				; CODE XREF: RefreshVolume+14j
		push	hl
		ld	hl, byte_1C07
		add	a, (hl)
		jp	m, loc_ABE
		ld	a, 0FFh

loc_ABE:				; CODE XREF: RefreshVolume+1Ej
		pop	hl

loc_ABF:				; CODE XREF: RefreshVolume+Ej
		and	7Fh
		ld	c, a
		ld	a, (de)
		rst	WriteFMIorII
		inc	de
		inc	hl
		djnz	loc_AA7
		pop	de
		ret
; End of function RefreshVolume

; ---------------------------------------------------------------------------

cfE7_Hold:				; DATA XREF: RAM:cfPtrTableo
		set	1, (ix+0)
		dec	de
		ret
; ---------------------------------------------------------------------------

cfE8_NoteStop:				; DATA XREF: RAM:cfPtrTableo
		call	TickMultiplier
		ld	(ix+1Eh), a
		ld	(ix+1Fh), a
		ret
; ---------------------------------------------------------------------------

cfEB_LoopExit:				; DATA XREF: RAM:cfPtrTableo
		inc	de
		add	a, 28h
		ld	c, a
		ld	b, 0
		push	ix
		pop	hl
		add	hl, bc
		ld	a, (hl)
		dec	a
		jp	z, loc_AEB
		inc	de
		ret
; ---------------------------------------------------------------------------

loc_AEB:				; CODE XREF: RAM:0AE6j
		xor	a
		ld	(hl), a
		jp	cfF6_GoTo
; ---------------------------------------------------------------------------

cfEC_ChgPSGVol:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	z
		res	4, (ix+0)
		dec	(ix+17h)
		add	a, (ix+6)
		cp	0Fh
		jp	c, loc_B06
		ld	a, 0Fh

loc_B06:				; CODE XREF: RAM:0B01j
		ld	(ix+6),	a
		ret
; ---------------------------------------------------------------------------

cfED_FMChnWrite:			; DATA XREF: RAM:cfPtrTableo
		call	ReadFMCommand
		rst	WriteFMIorII
		ret
; ---------------------------------------------------------------------------

cfEE_FM1Write:				; DATA XREF: RAM:cfPtrTableo
		call	ReadFMCommand
		call	WriteFMI
		ret

; =============== S U B	R O U T	I N E =======================================


ReadFMCommand:				; CODE XREF: RAM:cfED_FMChnWritep
					; RAM:cfEE_FM1Writep
		ex	de, hl
		ld	a, (hl)
		inc	hl
		ld	c, (hl)
		ex	de, hl
		ret
; End of function ReadFMCommand

; ---------------------------------------------------------------------------

cfEF_SetIns:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		jr	nz, loc_B55
		call	SetMaxRelRate
		ld	a, (de)
		ld	(ix+8),	a
		or	a
		jp	p, loc_B4B
		inc	de
		ld	a, (de)
		ld	(ix+0Fh), a

; =============== S U B	R O U T	I N E =======================================


SetInsFromSong:				; CODE XREF: PlaySoundID+742p
		push	de
		ld	a, (ix+0Fh)
		sub	81h
		ld	hl, MusicPtrs
		rst	ReadPtrTable
		ld	a, (hl)
		inc	hl
		ld	h, (hl)
		ld	l, a
		ld	a, (ix+8)
		and	7Fh
		ld	b, a
		call	JumpToInsData
		jr	loc_B50
; ---------------------------------------------------------------------------

loc_B4B:				; CODE XREF: RAM:0B2Aj
		push	de
		ld	b, a
		call	GetFMInsPtr

loc_B50:				; CODE XREF: SetInsFromSong+17j
		call	SendFMIns
		pop	de
		ret
; End of function SetInsFromSong

; ---------------------------------------------------------------------------

loc_B55:				; CODE XREF: RAM:0B20j
		or	a
		ret	p
		inc	de
		ret
; ---------------------------------------------------------------------------

cfF0_ModSetup:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+20h), e
		ld	(ix+21h), d
		ld	(ix+7),	80h
		inc	de
		inc	de
		inc	de
		ret
; ---------------------------------------------------------------------------

cfF1_ModTypePFM:			; DATA XREF: RAM:cfPtrTableo
		inc	de
		bit	7, (ix+1)
		jr	nz, cfF4_ModType
		ld	a, (de)

cfF4_ModType:				; CODE XREF: RAM:0B6Cj
					; DATA XREF: RAM:cfPtrTableo
		ld	(ix+7),	a
		ret
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR PlaySoundID

cfF2_StopTrk:				; CODE XREF: PlaySoundID+4Dj RAM:0A72j
					; DATA XREF: ...
		res	7, (ix+0)
		ld	a, 1Fh
		ld	(byte_1C15), a
		call	DoNoteOff
		ld	c, (ix+1)
		push	ix
		call	GetSFXChnPtrs
		ld	a, (byte_1C19)
		or	a
		jp	z, loc_C22
		xor	a
		ld	(byte_1C18), a
		bit	7, (iy+0)
		jr	z, loc_BAA
		ld	a, (ix+1)
		cp	(iy+1)
		jr	nz, loc_BAA
		push	iy
		ld	l, (iy+2Ah)
		ld	h, (iy+2Bh)
		jr	loc_BAE
; ---------------------------------------------------------------------------

loc_BAA:				; CODE XREF: PlaySoundID+6FDj
					; PlaySoundID+705j
		push	hl
		ld	hl, (word_1C37)

loc_BAE:				; CODE XREF: PlaySoundID+70Fj
		pop	ix
		res	2, (ix+0)
		bit	7, (ix+1)
		jr	nz, loc_C27
		bit	7, (ix+0)
		jr	z, loc_C22
		ld	a, 2
		cp	(ix+1)
		jr	nz, loc_BD4
		ld	a, 4Fh
		bit	0, (ix+0)
		jr	nz, loc_BD1
		and	0Fh

loc_BD1:				; CODE XREF: PlaySoundID+734j
		call	SendFM3SpcMode

loc_BD4:				; CODE XREF: PlaySoundID+72Cj
		ld	a, (ix+8)
		or	a
		jp	p, loc_BE0
		call	SetInsFromSong
		jr	loc_C1F
; ---------------------------------------------------------------------------

loc_BE0:				; CODE XREF: PlaySoundID+73Fj
		ld	b, a
		push	hl
		ld	hl, byte_1C04
		ld	a, (hl)
		ld	hl, 6000h
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		pop	hl
		call	JumpToInsData
		call	SendFMIns
		push	hl
		ld	hl, 6000h
		xor	a
		ld	e, 1
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), a
		ld	(hl), e
		ld	(hl), e
		ld	(hl), e
		ld	(hl), a
		ld	(hl), a
		pop	hl
		ld	a, (ix+18h)
		or	a
		jp	p, loc_C22
		ld	e, (ix+19h)
		ld	d, (ix+1Ah)

loc_C1F:				; CODE XREF: PlaySoundID+745j
		call	SendSSGEG

loc_C22:				; CODE XREF: PlaySoundID+6F2j
					; PlaySoundID+725j ...
		pop	ix
		pop	hl
		pop	hl
		ret
; ---------------------------------------------------------------------------

loc_C27:				; CODE XREF: PlaySoundID+71Fj
		bit	0, (ix+0)
		jr	z, loc_C22
		ld	a, (ix+1Ah)
		or	a
		jp	p, loc_C37
		ld	(7F11h), a

loc_C37:				; CODE XREF: PlaySoundID+798j
		jr	loc_C22
; END OF FUNCTION CHUNK	FOR PlaySoundID
; ---------------------------------------------------------------------------

cfF3_PSGNoise:				; DATA XREF: RAM:cfPtrTableo
		bit	2, (ix+1)
		ret	nz
		ld	a, 0DFh
		ld	(7F11h), a
		ld	a, (de)
		ld	(ix+1Ah), a
		set	0, (ix+0)
		or	a
		jr	nz, loc_C54
		res	0, (ix+0)
		ld	a, 0FFh

loc_C54:				; CODE XREF: RAM:0C4Cj
		ld	(7F11h), a
		ret
; ---------------------------------------------------------------------------

cfF5_SetPSGIns:				; DATA XREF: RAM:cfPtrTableo
		bit	7, (ix+1)
		ret	z
		ld	(ix+8),	a
		ret
; ---------------------------------------------------------------------------

cfF6_GoTo:				; CODE XREF: RAM:0AEDj	RAM:0C79j
					; DATA XREF: ...
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		dec	de
		ret
; ---------------------------------------------------------------------------

cfF7_Loop:				; DATA XREF: RAM:cfPtrTableo
		inc	de
		add	a, 28h
		ld	c, a
		ld	b, 0
		push	ix
		pop	hl
		add	hl, bc
		ld	a, (hl)
		or	a
		jr	nz, loc_C77
		ld	a, (de)
		ld	(hl), a

loc_C77:				; CODE XREF: RAM:0C73j
		inc	de
		dec	(hl)
		jp	nz, cfF6_GoTo
		inc	de
		ret
; ---------------------------------------------------------------------------

cfF8_GoSub:				; DATA XREF: RAM:cfPtrTableo
		ld	c, a
		inc	de
		ld	a, (de)
		ld	b, a
		push	bc
		push	ix
		pop	hl
		dec	(ix+9)
		ld	c, (ix+9)
		dec	(ix+9)
		ld	b, 0
		add	hl, bc
		ld	(hl), d
		dec	hl
		ld	(hl), e
		pop	de
		dec	de
		ret
; ---------------------------------------------------------------------------

cfF9_Return:				; DATA XREF: RAM:cfPtrTableo
		push	ix
		pop	hl
		ld	c, (ix+9)
		ld	b, 0
		add	hl, bc
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	(ix+9)
		inc	(ix+9)
		ret
; ---------------------------------------------------------------------------

cfFA_TickMult:				; DATA XREF: RAM:cfPtrTableo
		ld	(ix+2),	a
		ret
; ---------------------------------------------------------------------------

cfFB_ChgTransp:				; DATA XREF: RAM:cfPtrTableo
		add	a, (ix+5)
		ld	(ix+5),	a
		ret
; ---------------------------------------------------------------------------

cfFC_PitchSlide:			; DATA XREF: RAM:cfPtrTableo
		cp	1
		jr	nz, loc_CBF
		set	5, (ix+0)
		ret
; ---------------------------------------------------------------------------

loc_CBF:				; CODE XREF: RAM:0CB8j
		res	1, (ix+0)
		res	5, (ix+0)
		xor	a
		ld	(ix+10h), a
		ret
; ---------------------------------------------------------------------------

cfFD_RawFrqMode:			; DATA XREF: RAM:cfPtrTableo
		cp	1
		jr	nz, loc_CD5
		set	3, (ix+0)
		ret
; ---------------------------------------------------------------------------

loc_CD5:				; CODE XREF: RAM:0CCEj
		res	3, (ix+0)
		ret
; ---------------------------------------------------------------------------

cfFE_SpcFM3Mode:			; DATA XREF: RAM:cfPtrTableo
		ld	a, (ix+1)
		cp	2
		jr	nz, SpcFM3_skip
		set	0, (ix+0)
		ex	de, hl
		call	GetFM3FreqPtr
		ld	b, 4

loc_CEB:				; CODE XREF: RAM:0CFDj
		push	bc
		ld	a, (hl)
		inc	hl
		push	hl
		ld	hl, FM3_FreqVals
		add	a, a
		ld	c, a
		ld	b, 0
		add	hl, bc
		ldi
		ldi
		pop	hl
		pop	bc
		djnz	loc_CEB
		ex	de, hl
		dec	de
		ld	a, 4Fh

; =============== S U B	R O U T	I N E =======================================


SendFM3SpcMode:				; CODE XREF: PlaySoundID:loc_BD1p
		ld	(byte_1C12), a
		ld	c, a
		ld	a, 27h
		call	WriteFMI
		ret
; End of function SendFM3SpcMode

; ---------------------------------------------------------------------------

SpcFM3_skip:				; CODE XREF: RAM:0CDFj
		inc	de
		inc	de
		inc	de
		ret
; ---------------------------------------------------------------------------
FM3_FreqVals:	dw 0, 132h, 18Eh, 1E4h,	234h, 27Eh, 2C2h, 2F0h ; DATA XREF: RAM:0CEFo
; ---------------------------------------------------------------------------

cfMetaCoordFlag:			; DATA XREF: RAM:cfPtrTableo
		ld	hl, cfMetaPtrTable
		rst	ReadPtrTable
		inc	de
		ld	a, (de)
		jp	(hl)
; ---------------------------------------------------------------------------

cf00_SetTempo:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(byte_1C14), a
		ld	(byte_1C13), a
		ret
; ---------------------------------------------------------------------------

cf01_PlaySnd:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(byte_1C09), a
		ret
; ---------------------------------------------------------------------------

cf02_MusPause:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(byte_1C11), a
		or	a
		jr	z, loc_D56
		push	ix
		push	de
		ld	ix, byte_1C40
		ld	b, 0Ah
		ld	de, 30h

loc_D45:				; CODE XREF: RAM:0D4Ej
		res	7, (ix+0)
		call	SendNoteOff
		add	ix, de
		djnz	loc_D45
		pop	de
		pop	ix
		jp	SilencePSG
; ---------------------------------------------------------------------------

loc_D56:				; CODE XREF: RAM:0D37j
		push	ix
		push	de
		ld	ix, byte_1C40
		ld	b, 0Ah
		ld	de, 30h

loc_D62:				; CODE XREF: RAM:0D68j
		set	7, (ix+0)
		add	ix, de
		djnz	loc_D62
		pop	de
		pop	ix
		ret
; ---------------------------------------------------------------------------

cf03_CopyMem:				; DATA XREF: RAM:cfMetaPtrTableo
		ex	de, hl
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ld	c, (hl)
		ld	b, 0
		inc	hl
		ex	de, hl
		ldir
		dec	de
		ret
; ---------------------------------------------------------------------------

cf04_TickMulAll:			; DATA XREF: RAM:cfMetaPtrTableo
		ld	b, 0Ah
		ld	hl, unk_1C42

loc_D81:				; CODE XREF: RAM:0D88j
		push	bc
		ld	bc, 30h
		ld	(hl), a
		add	hl, bc
		pop	bc
		djnz	loc_D81
		ret
; ---------------------------------------------------------------------------

cf05_SSGEG:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(ix+18h), 80h
		ld	(ix+19h), e
		ld	(ix+1Ah), d

; =============== S U B	R O U T	I N E =======================================


SendSSGEG:				; CODE XREF: PlaySoundID:loc_C1Fp
		ld	hl, SSGEG_Ops
		ld	b, 4

loc_D9A:				; CODE XREF: SendSSGEG+Bj
		ld	a, (de)
		inc	de
		ld	c, a
		ld	a, (hl)
		inc	hl
		rst	18h
		djnz	loc_D9A
		dec	de
		ret
; End of function SendSSGEG

; ---------------------------------------------------------------------------

cf06_FMVolEnv:				; DATA XREF: RAM:cfMetaPtrTableo
		ld	(ix+18h), a
		inc	de
		ld	a, (de)
		ld	(ix+19h), a
		ret
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR UpdateTrack

UpdatePSGTrk:				; CODE XREF: UpdateTrack+4j
		call	TrackTimeout
		jr	nz, loc_DBF
		call	TrkUpdate_Proc
		bit	4, (ix+0)
		ret	nz
		call	PrepareModulat
		jr	loc_DCB
; ---------------------------------------------------------------------------

loc_DBF:				; CODE XREF: UpdateTrack+CC0j
		ld	a, (ix+1Eh)
		or	a
		jr	z, loc_DCB
		dec	(ix+1Eh)
		jp	z, SetRest

loc_DCB:				; CODE XREF: UpdateTrack+CCDj
					; UpdateTrack+CD3j
		call	DoPitchSlide
		call	DoModulation
		bit	2, (ix+0)
		ret	nz
		ld	c, (ix+1)
		ld	a, l
		and	0Fh
		or	c
		ld	(7F11h), a
		ld	a, l
		and	0F0h
		or	h
		rrca
		rrca
		rrca
		rrca
		ld	(7F11h), a
		ld	a, (ix+8)
		or	a
		ld	c, 0
		jr	z, loc_DFC
		dec	a
		ld	hl, VolEnvPtrs
		rst	ReadPtrTable
		call	DoPSGVolEnv
		ld	c, a

loc_DFC:				; CODE XREF: UpdateTrack+D01j
		bit	4, (ix+0)
		ret	nz
		ld	a, (ix+6)
		add	a, c
		bit	4, a
		jr	z, loc_E0B
		ld	a, 0Fh

loc_E0B:				; CODE XREF: UpdateTrack+D17j
		or	(ix+1)
		add	a, 10h
		bit	0, (ix+0)
		jr	nz, loc_E1A
		ld	(7F11h), a
		ret
; ---------------------------------------------------------------------------

loc_E1A:				; CODE XREF: UpdateTrack+D24j
		add	a, 20h ; ' '
		ld	(7F11h), a
		ret
; END OF FUNCTION CHUNK	FOR UpdateTrack
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR DoPSGVolEnv

loc_E20:				; CODE XREF: DoPSGVolEnv+1Bj
					; DoPSGVolEnv+26j
		ld	(ix+17h), a
; END OF FUNCTION CHUNK	FOR DoPSGVolEnv

; =============== S U B	R O U T	I N E =======================================


DoPSGVolEnv:				; CODE XREF: DoFMVolEnv+Bp
					; UpdateTrack+D08p

; FUNCTION CHUNK AT 0E20 SIZE 00000003 BYTES

		push	hl
		ld	c, (ix+17h)
		ld	b, 0
		add	hl, bc
		ld	a, (hl)
		pop	hl
		bit	7, a
		jr	z, loc_E51
		cp	83h ; 'É'
		jr	z, loc_E40
		cp	81h ; 'Å'
		jr	z, loc_E4B
		cp	80h ; 'Ä'
		jr	z, loc_E48
		inc	bc
		ld	a, (bc)
		jr	loc_E20
; ---------------------------------------------------------------------------

loc_E40:				; CODE XREF: DoPSGVolEnv+Fj
		set	4, (ix+0)
		pop	hl
		jp	SetRest
; ---------------------------------------------------------------------------

loc_E48:				; CODE XREF: DoPSGVolEnv+17j
		xor	a
		jr	loc_E20
; ---------------------------------------------------------------------------

loc_E4B:				; CODE XREF: DoPSGVolEnv+13j
		pop	hl
		set	4, (ix+0)
		ret
; ---------------------------------------------------------------------------

loc_E51:				; CODE XREF: DoPSGVolEnv+Bj
		inc	(ix+17h)
		ret
; End of function DoPSGVolEnv


; =============== S U B	R O U T	I N E =======================================


SetRest:				; CODE XREF: TrkUpdate_Proc+2Dp
					; UpdateTrack+CD8j ...
		set	4, (ix+0)
		bit	2, (ix+0)
		ret	nz
; End of function SetRest


; =============== S U B	R O U T	I N E =======================================


SilencePSGChn:				; CODE XREF: GetSFXChnPtrs+Ep
		ld	a, 1Fh
		add	a, (ix+1)
		or	a
		ret	p
		ld	(7F11h), a
		bit	0, (ix+0)
		ret	z
		ld	a, 0FFh
		ld	(7F11h), a
		ret
; End of function SilencePSGChn

; ---------------------------------------------------------------------------

DACLoop:				; CODE XREF: RAM:0076j	RAM:0F61j ...
		ei
		ld	a, (byte_1C3C)
		or	a
		jp	z, loc_E97
		ld	hl, SmplTable
		dec	a
		ld	c, a
		ld	b, 0
		add	hl, bc
		add	hl, bc
		add	hl, bc
		add	hl, bc
		add	hl, bc
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ld	c, (hl)
		inc	hl
		ld	b, (hl)
		inc	hl
		ld	a, (hl)
		ld	(byte_1C05), a
		xor	a
		ld	(byte_1C3C), a

loc_E97:				; CODE XREF: RAM:0E78j
		exx
		ld	a, (byte_1C3D)
		or	a
		jp	z, loc_EA7
		ld	(byte_1C08), a
		ld	hl, byte_1C40
		set	2, (hl)

loc_EA7:				; CODE XREF: RAM:0E9Cj
		ld	a, (byte_1C08)
		or	a
		jp	z, loc_ECD
		ld	hl, SmplTable
		dec	a
		ld	c, a
		ld	b, 0
		add	hl, bc
		add	hl, bc
		add	hl, bc
		add	hl, bc
		add	hl, bc
		ld	e, (hl)
		inc	hl
		ld	d, (hl)
		inc	hl
		ld	c, (hl)
		inc	hl
		ld	b, (hl)
		inc	hl
		ld	a, (hl)
		ld	(byte_1C06), a
		xor	a
		ld	(byte_1C3D), a
		ld	(byte_1C08), a

loc_ECD:				; CODE XREF: RAM:0EABj
		exx
		di
		ld	hl, byte_1C05
		ld	a, (hl)
		ld	hl, 6000h
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	a, (de)
		ei
		ld	(byte_1C3E), a
		dec	bc
		ld	a, c
		or	b
		jp	nz, loc_EFB
		ld	de, byte_F7F
		ld	bc, 8
		jp	loc_F08
; ---------------------------------------------------------------------------

loc_EFB:				; CODE XREF: RAM:0EEFj
		inc	de
		ld	a, e
		or	d
		jp	nz, loc_F08
		ld	de, 8000h
		ld	hl, byte_1C05
		inc	(hl)

loc_F08:				; CODE XREF: RAM:0EF8j	RAM:0EFEj
		exx
		di
		ld	hl, byte_1C06
		ld	a, (hl)
		ld	hl, 6000h
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		rra
		ld	(hl), a
		xor	a
		ld	(hl), a
		ld	a, (de)
		ei
		ld	(byte_1C3F), a
		dec	bc
		ld	a, c
		or	b
		jp	nz, loc_F3B
		ld	de, byte_F7F
		ld	bc, 8
		ld	hl, byte_1C40
		res	2, (hl)
		jp	loc_F48
; ---------------------------------------------------------------------------

loc_F3B:				; CODE XREF: RAM:0F2Aj
		inc	de
		ld	a, e
		or	d
		jp	nz, loc_F48
		ld	de, 8000h
		ld	hl, byte_1C06
		inc	(hl)

loc_F48:				; CODE XREF: RAM:0F38j	RAM:0F3Ej
		exx
		ld	a, 2Ah
		di
		ld	(4000h), a
		ld	a, (byte_1C3E)
		ld	hl, byte_1C3F
		add	a, (hl)
		jp	c, loc_F6C
		jp	p, loc_F64
		sub	80h
		ld	(4001h), a
		jp	DACLoop
; ---------------------------------------------------------------------------

loc_F64:				; CODE XREF: RAM:0F59j
		ld	a, 0
		ld	(4001h), a
		jp	DACLoop
; ---------------------------------------------------------------------------

loc_F6C:				; CODE XREF: RAM:0F56j
		jp	m, loc_F77
		sub	80h
		ld	(4001h), a
		jp	DACLoop
; ---------------------------------------------------------------------------

loc_F77:				; CODE XREF: RAM:loc_F6Cj
		ld	a, 0FFh
		ld	(4001h), a
		jp	DACLoop
; ---------------------------------------------------------------------------
byte_F7F:	db 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h ; DATA XREF: RAM:0068o
					; RAM:006Fo ...
		db 80h,	80h, 80h, 80h, 80h, 80h, 80h, 80h
VolEnvPtrs:	dw byte_FA7, byte_FA9, byte_FB6, byte_FC7, byte_FD4, byte_FD9
					; DATA XREF: DoFMVolEnv+7o
					; UpdateTrack+D04o
		dw byte_FF0, byte_FF9, byte_100A, byte_1015, byte_102A
		dw byte_1034
byte_FA7:	db 2, 83h		; DATA XREF: RAM:VolEnvPtrso
byte_FA9:	db 0, 1, 2, 3, 4, 4, 4,	4, 5, 6, 7, 8, 81h ; DATA XREF:	RAM:VolEnvPtrso
byte_FB6:	db 0, 0, 1, 1, 2, 2, 2,	3, 3, 4, 4, 5, 5, 6, 6,	7, 81h
					; DATA XREF: RAM:VolEnvPtrso
byte_FC7:	db 4, 3, 2, 1, 1, 2, 2,	3, 3, 4, 4, 5, 81h ; DATA XREF:	RAM:VolEnvPtrso
byte_FD4:	db 0, 0, 1, 1, 81h	; DATA XREF: RAM:VolEnvPtrso
byte_FD9:	db 0, 0, 0, 1, 1, 1, 2,	2, 2, 3, 3, 3, 4, 4, 4,	5, 5, 5
					; DATA XREF: RAM:VolEnvPtrso
		db 6, 6, 6, 7, 81h
byte_FF0:	db 1, 0Ch, 3, 0Fh, 2, 7, 3, 0Fh, 80h ; DATA XREF: RAM:VolEnvPtrso
byte_FF9:	db 0, 0, 0, 2, 3, 3, 4,	5, 6, 7, 8, 9, 0Ah, 0Bh, 0Eh, 0Fh
					; DATA XREF: RAM:VolEnvPtrso
		db 83h
byte_100A:	db 3, 2, 1, 1, 0, 0, 1,	2, 3, 4, 81h ; DATA XREF: RAM:VolEnvPtrso
byte_1015:	db 1, 0, 0, 0, 0, 1, 1,	1, 2, 2, 2, 3, 3, 3, 3,	4, 4, 4
					; DATA XREF: RAM:VolEnvPtrso
		db 5, 5, 81h
byte_102A:	db 10h,	20h, 30h, 40h, 30h, 20h, 10h, 0, 0F0h, 80h
					; DATA XREF: RAM:VolEnvPtrso
byte_1034:	db 0, 0, 1, 1, 3, 3, 4,	5, 83h ; DATA XREF: RAM:VolEnvPtrso
ModEnvPtrs:	dw byte_1051, byte_105D, byte_106A, byte_1076, byte_10B8
					; DATA XREF: DoModulation+53o
		dw byte_10ED, byte_112A, byte_1144, byte_115E, byte_1166
byte_1051:	db 40h,	60h, 70h, 60h, 50h, 30h, 10h, 0F0h, 0D0h, 0B0h
					; DATA XREF: RAM:ModEnvPtrso
		db 90h,	83h
byte_105D:	db   0,	 2,  4,	 6,  8,	10, 12,	14, 16,	18, 20,	24
					; DATA XREF: RAM:ModEnvPtrso
		db  81h
byte_106A:	db   0,	 0,  1,	 3,  1,	 0, -1,	-3, -1,	 0 ; DATA XREF:	RAM:ModEnvPtrso
		db  82h,   2
byte_1076:	db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
					; DATA XREF: RAM:ModEnvPtrso
		db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
		db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
		db   0,	 2,  4,	 6,  8,	10, 12,	10,  8,	 6,  4,	 2,  0
		db  -2,	-4, -6,	-8,-10,-12,-10,	-8, -6,	-4, -2,	 0
		db  82h, 29h
byte_10B8:	db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
					; DATA XREF: RAM:ModEnvPtrso
		db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
		db   0,	 0,  2,	 4,  6,	 8, 10,	12, 10,	 8,  6,	 4,  2
		db   0,	-2, -4,	-6, -8,-10,-12,-10, -8,	-6, -4,	-2
		db  82h, 1Bh
byte_10ED:	db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
					; DATA XREF: RAM:ModEnvPtrso
		db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
		db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
		db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 3,  6
		db   3,	 0, -3,	-6, -6,	-3,  0
		db  82h, 33h
byte_112A:	db   0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
					; DATA XREF: RAM:ModEnvPtrso
		db   0,	 0,  0,	 2,  4,	 2,  0,	-2, -4,	-2,  0
		db  82h, 11h
byte_1144:	db  -2,	-1,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0,	 0,  0
					; DATA XREF: RAM:ModEnvPtrso
		db   0,	 0,  0,	 0,  0,	 1,  1,	 0,  0,	-1, -1
		db  82h, 11h
byte_115E:	db   3,	 2,  1,	 0,  0,	 0,  1 ; DATA XREF: RAM:ModEnvPtrso
		db  81h
byte_1166:	db   0,	 0,  0,	 0,  1,	 1,  1,	 1,  2,	 2,  1,	 1,  1
					; DATA XREF: RAM:ModEnvPtrso
		db   0,	 0,  0
		db  84h,   1, 82h,   4
MusicBanks:	db 75h,	75h, 75h, 75h, 75h, 75h, 75h, 75h, 75h,	74h, 74h
					; DATA XREF: PlaySoundID+59o
		db 74h,	74h, 74h, 74h, 75h, 75h, 75h, 75h, 75h,	75h, 75h
		db 75h,	75h, 75h, 74h, 74h, 74h, 74h, 74h, 74h
MusicPtrs:	dw 8000h, 8099h, 8384h,	86A4h, 9CA6h, 0A982h, 0C038h, 0CFE7h
					; DATA XREF: PlaySoundID+7Eo
					; SetInsFromSong+6o
		dw 0D9DBh, 0C500h, 0D6F4h, 0E637h, 0D6F4h, 0D6F4h, 0D6F4h
		dw 8069h, 8069h, 8354h,	8674h, 9C76h, 0A952h, 0C008h, 0CFB7h
		dw 0D9ABh, 0E7B6h, 0D6C4h, 0E607h, 0FCFBh, 0E607h, 0E607h
		dw 0E607h
SFXPtrs:	dw 0F800h, 0F80Dh, 0F81Ah, 0F827h, 0F834h, 0F841h, 0F84Eh
					; DATA XREF: PlaySoundID+14Ao
		dw 0F85Bh, 0F868h, 0F875h, 0F882h, 0F88Fh, 0F89Ch, 0F8A9h
		dw 0F8B6h, 0F8C3h, 0F8D0h, 0F8DDh, 0F8EAh, 0F8F7h, 0F904h
		dw 0F911h, 0F91Eh, 0F92Bh, 0F938h, 0F945h, 0F952h, 0F95Fh
		dw 0F96Ch, 0F979h, 0F986h, 0F993h, 0F9A0h, 0F9ADh, 0F9BAh
		dw 0F9C7h, 0F9D4h, 0F9E1h, 0F9EEh, 0F9FBh, 0FA08h, 0FA15h
		dw 0FA22h, 0FA2Fh, 0FA3Ch, 0FA49h, 0FA56h, 0FA63h, 0FA70h
		dw 0FA7Dh, 0FA8Ah, 0FA97h, 0FAA4h, 0FAB1h, 0FABEh, 0FACBh
		dw 0FAD8h, 0FAE5h, 0FAF2h, 0FAFFh, 0FB0Ch, 0FB7Eh, 0FB8Bh
		dw 0FB98h, 0FBA5h, 0FBB2h, 0FBBFh, 0FBCCh, 0FBD9h, 0FBE6h
		dw 0FBF3h, 0FC00h, 0FC0Dh
SpcSFXPtrs:	dw 0F800h, 0F80Dh, 0F827h ; DATA XREF: PlaySoundID+130o
SndPriorities:	db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
					; DATA XREF: DoSoundQueue+17o
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
		db   7Fh,  7Fh,	 7Fh,  7Fh,  7Fh
SmplTable:	DACTable < 8000h,   6CEh,    76h> ; DATA XREF: RAM:0E7Bo
					; RAM:0EAEo
		DACTable < 86CEh,   9BCh,    76h>
		DACTable < 908Ah,   9DCh,    76h>
		DACTable < 9A66h,  0D64h,    76h>
		DACTable <0A7CAh,  1522h,    76h>
		DACTable <0BCECh,   6CEh,    76h>
		DACTable <0C3BAh,   6CEh,    76h>
		DACTable <0CA88h,   6CEh,    76h>
		DACTable <0D156h,   6CEh,    76h>
		DACTable <0D824h,   6CEh,    76h>
		DACTable <0DEF2h,   6CEh,    76h>
		DACTable <0E5C0h,   6CEh,    76h>
		DACTable <0EC8Eh,   6CEh,    76h>
		DACTable <0F35Ch,   6CEh,    76h>
		DACTable <0FA2Ah,   6CEh,    76h>
		DACTable < 80F8h,   6CEh,    77h>
		DACTable < 87C6h,  1790h,    77h>
		DACTable < 9F56h,   528h,    77h>
		DACTable <0A47Eh,  1630h,    77h>
		DACTable <0BAAEh,   740h,    77h>
		DACTable <0C1EEh,   53Ch,    77h>
		DACTable <0C72Ah,  3A90h,    77h>
		DACTable < 81BAh,  0E7Ch,    78h>
		DACTable < 9036h,  5610h,    78h>
		DACTable <0E646h,   7B2h,    78h>
		DACTable <0EDF8h,  248Ah,    78h>
		DACTable < 9282h,  4988h,    79h>
		DACTable <0DC0Ah,   440h,    79h>
		DACTable <0E04Ah,  0E22h,    79h>
		DACTable <0EE6Ch,  3AECh,    79h>
		DACTable <0A958h,  0E58h,    7Ah>
		DACTable <0B7B0h,  0AAEh,    7Ah>
		DACTable <0C25Eh,  127Ch,    7Ah>
		DACTable <0D4DAh,   528h,    7Ah>
		DACTable <0DA02h,  0AA4h,    7Ah>
		DACTable <0E4A6h,  14CCh,    7Ah>
		DACTable <0F972h,   4F2h,    7Ah>
		DACTable <0FE64h,  0A7Ch,    7Ah>
		DACTable < 88E0h,  1106h,    7Bh>
		DACTable < 99E6h,  1E7Eh,    7Bh>
		DACTable <0B864h,  1746h,    7Bh>
		DACTable <0CFAAh,  1888h,    7Bh>
		DACTable <0E832h,  1D32h,    7Bh>
		DACTable < 8564h,  1346h,    7Ch>
		DACTable < 98AAh,  1236h,    7Ch>
		DACTable <0AAE0h,  1736h,    7Ch>
		DACTable <0C216h,  114Ah,    7Ch>
		DACTable <0D360h,  10F4h,    7Ch>
		DACTable <0E454h,  0BE8h,    7Ch>
		DACTable <0F03Ch,  1124h,    7Ch>
		DACTable < 8160h,  0F8Ch,    7Dh>
		DACTable < 90ECh,  0F88h,    7Dh>
		DACTable <0A074h,  0E16h,    7Dh>
		DACTable <0AE8Ah,  10BCh,    7Dh>
		DACTable <0BF46h,   8ACh,    7Dh>
		DACTable <0C7F2h,   96Ch,    7Dh>
		DACTable <0D15Eh,   890h,    7Dh>
		DACTable <0D9EEh,  0B4Ah,    7Dh>
		DACTable <0E538h,  1D42h,    7Dh>
		DACTable < 827Ah,   72Ah,    7Eh>
		DACTable < 89A4h,  2290h,    7Eh>
		DACTable <0AC34h,   754h,    7Eh>
		DACTable <0B388h,   7F8h,    7Eh>
		DACTable <0BB80h,  1090h,    7Eh>
		DACTable <0CC10h,  1180h,    7Eh>
		DACTable <0DD90h,  1008h,    7Eh>
		DACTable <0ED98h,   98Ch,    7Eh>
		DACTable <0F724h,   7AEh,    7Eh>
		DACTable <0FED2h,   8CAh,    7Eh>
		DACTable < 879Ch,  11E8h,    7Fh>
		DACTable < 9984h,  40F2h,    7Fh>
		DACTable <0DA76h,   7B8h,    7Fh>
		ds 7CAh
		ds 1
		ds 1
		ds 1
		ds 1
byte_1C04:	ds 1			; DATA XREF: RAM:0059w	UpdateAll+13o ...
byte_1C05:	ds 1			; DATA XREF: RAM:005Ew	RAM:0E90w ...
byte_1C06:	ds 1			; DATA XREF: RAM:0EC3w	RAM:0F0Ao ...
byte_1C07:	ds 1			; DATA XREF: DoFading+3Co
					; StopAllSound+24w ...
byte_1C08:	ds 1			; DATA XREF: DrumUpdate_Proc+2Fw
					; RAM:0E9Fw ...
byte_1C09:	ds 1			; DATA XREF: PlaySoundIDr
					; StopAllSound-235w ...
unk_1C0A:	ds 1			; DATA XREF: StopAllSound+3o
					; DoSoundQueue+3Do
		ds 1
		ds 1
byte_1C0D:	ds 1			; DATA XREF: DoPause+13r RAM:0753w ...
byte_1C0E:	ds 1			; DATA XREF: RAM:075Bw
					; DoFading:ApplyFadingr
byte_1C0F:	ds 1			; DATA XREF: RAM:0758w	DoFading+Br ...
unk_1C10:	ds 1			; DATA XREF: DoPauseo
byte_1C11:	ds 1			; DATA XREF: DoPause:loc_718r
					; RAM:cf02_MusPausew
byte_1C12:	ds 1			; DATA XREF: StopAllSound+34w
					; SendFM3SpcModew
byte_1C13:	ds 1			; DATA XREF: PlaySoundID+91w
					; DoTempo+3o ...
byte_1C14:	ds 1			; DATA XREF: PlaySoundID+94w DoTempor	...
byte_1C15:	ds 1			; DATA XREF: PlaySoundID+15Bw
					; PlaySoundID+6E0w
byte_1C16:	ds 1			; DATA XREF: RAM:cfE2_SetCommw
byte_1C17:	ds 1			; DATA XREF: DoSoundQueue+2w
byte_1C18:	ds 1			; DATA XREF: PlaySoundID+23w
					; DoSoundQueue+1Fr ...
byte_1C19:	ds 1			; DATA XREF: UpdateAll+10w
					; UpdateSFXTracks+2w ...
unk_1C1A:	ds 1			; DATA XREF: GetFM3FreqPtr+8o
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
unk_1C22:	ds 1			; DATA XREF: GetFM3FreqPtr+Co
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
unk_1C2A:	ds 1			; DATA XREF: GetFM3FreqPtro
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
byte_1C32:	ds 1			; DATA XREF: GetSFXChnPtrs+25w
word_1C33:	ds 2			; DATA XREF: PlaySoundID+9Bw
					; PlaySoundID+BAr ...
word_1C35:	ds 2			; DATA XREF: PlaySoundID+A1w
					; PlaySoundID+AEr ...
word_1C37:	ds 2			; DATA XREF: GetFMInsPtrr
					; PlaySoundID+88w ...
word_1C39:	ds 2			; DATA XREF: PlaySoundID+157w
					; PlaySoundID+1B2r
byte_1C3B:	ds 1			; DATA XREF: PlaySoundID+165w
					; PlaySoundID+18Fr
byte_1C3C:	ds 1			; DATA XREF: StopAllSound+27w
					; RAM:0E74r ...
byte_1C3D:	ds 1			; DATA XREF: StopAllSound+2Aw
					; RAM:cfEA_PlayDACw ...
byte_1C3E:	ds 1			; DATA XREF: RAM:0EE9w	RAM:0F4Fr
byte_1C3F:	ds 1			; DATA XREF: RAM:0F24w	RAM:0F52o
byte_1C40:	ds 1			; DATA XREF: UpdateAll+2Bo
					; PlaySoundID+A4o ...
		ds 1
unk_1C42:	ds 1			; DATA XREF: RAM:0D7Eo
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
unk_1C4B:	ds 1			; DATA XREF: DoTempo+9o
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
unk_1C70:	ds 1			; DATA XREF: UpdateAll+38o
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
byte_1D60:	ds 1			; DATA XREF: StopDrumPSG+4w
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
byte_1D90:	ds 1			; DATA XREF: PlaySoundID+DCo
					; StopDrumPSG+Aw
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
byte_1DC0:	ds 1			; DATA XREF: StopDrumPSG+Dw
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
byte_1DF0:	ds 1			; DATA XREF: StopDrumPSG+7w
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
unk_1E20:	ds 1			; DATA XREF: UpdateSFXTracks+14o
					; DoPause+39o
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
unk_1F70:	ds 1			; DATA XREF: UpdateSFXTracks+24o
					; PlaySoundID:StopSpcSFXo
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
		ds 1
; end of 'RAM'


		end
